apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: telegram
  name: telegram
spec:
  type: LoadBalancer
  ports:
    - name: "12069"
      port: 12069
      targetPort: 12069
  selector:
    io.kompose.service: telegram
