version: '3.9'

services:
  uniexplorers-frontend:
    container_name: uniexplorers-frontend
    image: jjlim159/uniexplorers-frontend
    build:
      dockerfile: Dockerfile
    env_file: ./.env
    restart: on-failure
    ports: 
      - 5173:80