build:
	docker compose build

push:
	docker push jjlim159/uniexplorers-user-server:latest && \
	docker push jjlim159/uniexplorers-image-server:latest && \
	docker push jjlim159/uniexplorers-uni-server:latest && \
	docker push jjlim159/uniexplorers-forum-server:latest && \
	docker push jjlim159/uniexplorers-location-server:latest && \
	docker push jjlim159/uniexplorers-chat-server:latest && \
	docker push jjlim159/uniexplorers-similarity-server:latest && \
	docker push jjlim159/uniexplorers-recommender:latest && \
	docker push jjlim159/uniexplorers-auth-server:latest && \
	docker push jjlim159/uniexplorers-mongodb:latest && \
	docker push jjlim159/uniexplorers-user-db:latest && \
	docker push jjlim159/uniexplorers-forum-db:latest && \
	docker push jjlim159/uniexplorers-uni-db:latest && \
	docker push jjlim159/uniexplorers-mongoseed:latest && \
	docker push jjlim159/uniexplorers-cache:latest && \
	docker push jjlim159/uniexplorers-seed-migration:latest && \
	docker push jjlim159/uniexplorers-ingestion:latest && \
	docker push jjlim159/uniexplorers-scraper:latest && \
	docker push jjlim159/uniexplorers-notif-server:latest && \
	docker push jjlim159/uniexplorers-kong:latest && \
	docker push jjlim159/uniexplorers-telegram:latest