apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: broker
  name: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: broker
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/uniexplorers-backend-default: "true"
        io.kompose.service: broker
    spec:
      containers:
        - image: rabbitmq:3-management
          livenessProbe:
            exec:
              command:
                - "rabbitmq-diagnostics"
                - "-q"
                - "ping"
            failureThreshold: 3
            periodSeconds: 30
            timeoutSeconds: 30
          name: broker
          ports:
            - containerPort: 5672
            - containerPort: 15672
      restartPolicy: Always
