apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: scraper
  name: scraper
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: scraper
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yml
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/uniexplorers-backend-default: "true"
        io.kompose.service: scraper
    spec:
      containers:
      - args:
        - python
        - scheduler.py
        env:
        - name: MONGO_HOST
          valueFrom:
            configMapKeyRef:
              key: MONGO_HOST
              name: mongo-env
        - name: MONGO_INITDB_DATABASE
          valueFrom:
            configMapKeyRef:
              key: MONGO_INITDB_DATABASE
              name: mongo-env
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: MONGO_INITDB_ROOT_PASSWORD
              name: mongo-env
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            configMapKeyRef:
              key: MONGO_INITDB_ROOT_USERNAME
              name: mongo-env
        - name: MONGO_PORT
          valueFrom:
            configMapKeyRef:
              key: MONGO_PORT
              name: mongo-env
        - name: PASSWORD
          valueFrom:
            configMapKeyRef:
              key: PASSWORD
              name: scraper-env
        - name: USERNAME
          valueFrom:
            configMapKeyRef:
              key: USERNAME
              name: scraper-env
        image: jjlim159/uniexplorers-scraper:latest
        name: scraper
      restartPolicy: Always
