apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: recommender
  name: recommender
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: recommender
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/uniexplorers-backend-default: "true"
        io.kompose.service: recommender
    spec:
      containers:
        - env:
            - name: UNI_API_URL
              valueFrom:
                configMapKeyRef:
                  key: UNI_API_URL
                  name: urls-env
            - name: USER_API_URL
              valueFrom:
                configMapKeyRef:
                  key: USER_API_URL
                  name: urls-env
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - curl --fail http://localhost:8080/api/healthcheck || exit 1
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 10
          image: jjlim159/uniexplorers-recommender:latest
          name: recommender
          ports:
            - containerPort: 8080
      restartPolicy: Always
