apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: uni-db
  name: uni-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: uni-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/uniexplorers-backend-default: "true"
        io.kompose.service: uni-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: uni-db-env
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: uni-db-env
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: uni-db-env
          livenessProbe:
            exec:
              command:
                - pg_isready 
                - -d 
                - $(POSTGRES_DB) 
                - -U 
                - $(POSTGRES_USER)
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          image: jjlim159/uniexplorers-uni-db:latest
          name: uni-database
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: uni-pg-data
      restartPolicy: Always
      volumes:
        - name: uni-pg-data
          persistentVolumeClaim:
            claimName: uni-pg-data
