apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: uni-pg-data
  name: uni-pg-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
